#!/usr/bin/env python3
"""Draw public/og.png — the share card every page falls back to.

Model pages pass their product photo to the layout and get a real card. Every
other page — the homepage, the fourteen category hubs, the brand index, the
carry-on tables, /privacy — passed nothing, so `og:image` was simply omitted
and a shared link rendered as a bare URL. This is the fallback that ends that.

Committed as a PNG rather than generated during the build, on purpose. It never
changes between deploys, Pillow is not otherwise a build dependency (only
image_bg.py uses it, and that runs in the nightly, not in Vercel's builder), and
a share card that fails to render is a failure nobody sees until someone posts a
link. A checked-in file cannot fail at build time. Re-run this by hand if the
mark or the palette changes:

    python3 scripts/og_image.py

Deliberately not a screenshot of the site. A screenshot at 1200x630 is mostly
filter rail and table header, and it is illegible at the size the card actually
appears — a few hundred pixels wide in a Slack channel. So: the mark, the name,
and one line saying what this is, sized to survive that.

The bison is the same geometry as src/components/Logo.astro and
public/favicon.svg, re-expressed for a renderer with no SVG parser. The body is
a pure polygon in the source path — every command is h/v/l/H/V — so it
transcribes exactly. The horns are the only curves, and they are evaluated here
rather than approximated. The one intentional difference is the muzzle notch:
Logo.astro cuts it as a real hole with fill-rule="evenodd" because the mark has
to survive being reversed out over a product photo, and warns against painting
it in the background colour. That warning does not apply to a fixed card on a
known flat field, where painting it is identical and needs no path winding.
"""

from __future__ import annotations

import pathlib
import sys

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:  # pragma: no cover - the message is the whole point
    sys.exit(
        "Pillow is not installed. It is not a build dependency and does not "
        "need to be one:\n    pip install -r requirements-image-bg.txt"
    )

# 1200x630 is the size every unfurler crops toward, and the one Slack, X,
# LinkedIn and iMessage all render as a large card rather than a thumbnail.
W, H = 1200, 630

# The dark theme's palette, from src/styles/app.css. Hardcoded rather than
# parsed: this file is regenerated by hand on the rare occasion the palette
# moves, and a CSS parser here would be more code than the drawing.
BG = "#191c1d"
INK = "#e8eae8"
INK_DIM = "#949c9a"
ACCENT = "#ff5a1f"
LINE = "#343a3b"

# The mark's own coordinate system, straight out of the SVG viewBox.
VIEWBOX = 32

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "public" / "og.png"

# The square mark, for schema.org's Organization.logo — see src/lib/schema.js
# for why that field cannot point at either of the two images that already
# existed. 512 rather than the documented 112 minimum because this is the image
# a knowledge panel renders at whatever size it likes and there is no reason to
# hand it the smallest legal one; it costs a couple of kilobytes.
LOGO_OUT = ROOT / "public" / "logo.png"
LOGO = 512

# Menlo ships with macOS and is one of the faces in the site's --mono stack, so
# the card is set in a font a reader could plausibly be seeing the site in.
# The fallbacks cover a Linux runner, should this ever move into CI.
FONT_CANDIDATES = [
    ("/System/Library/Fonts/Menlo.ttc", 0),
    ("/System/Library/Fonts/SFNSMono.ttf", 0),
    ("/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf", 0),
    ("/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf", 0),
]


def load_font(size: int) -> ImageFont.FreeTypeFont:
    for path, index in FONT_CANDIDATES:
        if pathlib.Path(path).exists():
            return ImageFont.truetype(path, size, index=index)
    sys.exit(
        "No monospaced font found in any of:\n  "
        + "\n  ".join(p for p, _ in FONT_CANDIDATES)
    )


def cubic(p0, p1, p2, p3, steps: int = 24):
    """Flatten one cubic Bezier to points.

    24 steps is well past what a 200px mark can show — the horn is a sliver a
    few pixels thick at its widest — and costs nothing at this size.
    """
    out = []
    for i in range(steps + 1):
        t = i / steps
        u = 1 - t
        out.append(
            (
                u * u * u * p0[0] + 3 * u * u * t * p1[0] + 3 * u * t * t * p2[0] + t * t * t * p3[0],
                u * u * u * p0[1] + 3 * u * u * t * p1[1] + 3 * u * t * t * p2[1] + t * t * t * p3[1],
            )
        )
    return out


def bison_paths():
    """The mark, in viewBox units: (polygons to fill, notch to cut).

    Transcribed from Logo.astro. The body path reads
        M9 9.8 h14 v6.4 l-2.4 2.1 v4.6 l-2.1 2.4 h-6.9 l-2.1 -2.4 v-4.6
        L7.9 16.2 V9.8 H9 z
    which is the shoulder hump and skull as one mass tapering in two steps to
    the muzzle. Each horn is two cubics — out along the top, back along the
    underside — closing into the sliver that reads as a horn at 14px.
    """
    body = [
        (9, 9.8), (23, 9.8), (23, 16.2), (20.6, 18.3), (20.6, 22.9),
        (18.5, 25.3), (11.6, 25.3), (9.5, 22.9), (9.5, 18.3), (7.9, 16.2),
        (7.9, 9.8),
    ]

    # Left horn: out to the tip at (2.5, 6.6), then back to (9, 9.7).
    left = cubic((9, 11.5), (5.6, 11.2), (3.2, 9.6), (2.5, 6.6))
    left += cubic((2.5, 6.6), (4.5, 8.8), (6.5, 9.7), (9, 9.7))

    # Right horn: the same shape mirrored about the mark's centre line.
    right = cubic((23, 11.5), (26.4, 11.2), (28.8, 9.6), (29.5, 6.6))
    right += cubic((29.5, 6.6), (27.5, 8.8), (25.5, 9.7), (23, 9.7))

    notch = [(13.4, 22.1), (18.6, 22.1), (18.6, 24.4), (13.4, 24.4)]

    return [body, left, right], notch


def draw_bison(draw: ImageDraw.ImageDraw, x: float, y: float, size: float, fill: str, hole: str):
    """Paint the mark with its viewBox top-left at (x, y), `size` px across."""
    k = size / VIEWBOX
    place = lambda pts: [(x + px * k, y + py * k) for px, py in pts]

    shapes, notch = bison_paths()
    for shape in shapes:
        draw.polygon(place(shape), fill=fill)
    draw.polygon(place(notch), fill=hole)


def ink_bounds():
    """The mark's actual extent in viewBox units, which is not the viewBox.

    The drawing occupies x 2.5-29.5 and y 6.6-25.3 of a 32-unit box, so laying
    it out by the box centres the *box* and leaves the mark sitting low with
    uneven side margins — the same trap the card's vertical placement note
    describes, and worse on a square where both axes show it. Measured rather
    than written down so it stays true if the mark is ever redrawn.
    """
    shapes, _ = bison_paths()
    xs = [p[0] for shape in shapes for p in shape]
    ys = [p[1] for shape in shapes for p in shape]
    return min(xs), min(ys), max(xs), max(ys)


def write(img: Image.Image, out: pathlib.Path, size: tuple[int, int]) -> None:
    img.resize(size, Image.LANCZOS).save(out, "PNG", optimize=True)
    print(f"wrote {out.relative_to(ROOT)} ({out.stat().st_size / 1024:.0f} KB)")


def draw_og() -> None:
    # Supersampled 3x and reduced at the end. The horns taper to well under a
    # pixel and Pillow's polygon fill has no antialiasing of its own, so drawn
    # at final size they come out as a staircase.
    scale = 3
    img = Image.new("RGB", (W * scale, H * scale), BG)
    draw = ImageDraw.Draw(img)

    margin = 88 * scale

    # A hairline of accent down the left edge. The card is mostly empty field
    # and needs one element that is not centred type to read as designed rather
    # than as a default.
    draw.rectangle([0, 0, 12 * scale, H * scale], fill=ACCENT)

    # Vertical placement is measured against the *ink*, not the boxes. The mark
    # is inset inside its own viewBox — the horns start at y=6.6 of 32 — so
    # laying it out by its top-left leaves a top margin half again the bottom
    # one, and the card reads as having slipped down the frame.
    mark = 132 * scale
    draw_bison(draw, margin, 98 * scale, mark, ACCENT, BG)

    name_font = load_font(104 * scale)
    tag_font = load_font(38 * scale)
    foot_font = load_font(27 * scale)

    # CARRYNERD, letterspaced by hand: the name is the one thing that has to be
    # legible at thumbnail size, and Pillow has no tracking control.
    name_y = 270 * scale
    x = margin
    for ch in "CARRYNERD":
        draw.text((x, name_y), ch, font=name_font, fill=INK)
        x += draw.textlength(ch, font=name_font) + 7 * scale

    # brand.js TAGLINE, which is what the <title> of every page already says.
    draw.text((margin, 400 * scale), "backpack spec index", font=tag_font, fill=ACCENT)

    draw.line(
        [(margin, 464 * scale), (W * scale - margin, 464 * scale)],
        fill=LINE,
        width=2 * scale,
    )

    # No counts on the card. A number here would be wrong within a night and
    # the file is not regenerated by the nightly — the description meta tag is
    # where the live figures belong, and it has them.
    draw.text(
        (margin, 490 * scale),
        "volume · weight · dimensions · price, normalised across brands",
        font=foot_font,
        fill=INK_DIM,
    )

    write(img, OUT, (W, H))


def draw_logo() -> None:
    """The mark alone on the brand field, square.

    No wordmark. This is read at whatever size the consumer chooses — a
    favicon-sized slot in one place, a panel in another — and "CARRYNERD" set
    across 512px survives the first and not the second. The card carries the
    name because a share card is read once at a known size; a logo is not.
    """
    scale = 3
    side = LOGO * scale
    img = Image.new("RGB", (side, side), BG)
    draw = ImageDraw.Draw(img)

    x0, y0, x1, y1 = ink_bounds()
    ink_w, ink_h = x1 - x0, y1 - y0

    # 72% of the frame on the mark's longer axis. Tighter reads as a crop when
    # the image is rendered inside a rounded container, which most of the
    # places this appears do.
    k = side * 0.72 / max(ink_w, ink_h)
    draw_bison(
        draw,
        (side - ink_w * k) / 2 - x0 * k,
        (side - ink_h * k) / 2 - y0 * k,
        VIEWBOX * k,
        ACCENT,
        BG,
    )

    write(img, LOGO_OUT, (LOGO, LOGO))


def main() -> None:
    draw_og()
    draw_logo()


if __name__ == "__main__":
    main()
